name: Storybook Preview

on:
  pull_request:
    branches:
      - seven
      - main

jobs:
  build-storybook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install

      - name: Build Storybook
        run: pnpm run build-storybook

      - name: Upload Storybook preview
        uses: actions/upload-artifact@v4
        with:
          name: storybook-preview
          path: storybook-static
